export interface ElephantSticker {
  id: string;
  packId: string;
  packName: string;
  title: string;
  caption: string;
  themeColor: 'red' | 'sky' | 'navy' | 'orange' | 'pink' | 'purple' | 'white';
  bgGradient: string;
  borderColor: string;
  textColor: string;
  badgeColor: string;
  pose: string;
  propsEmoji: string;
  aiPrompt: string;
  defaultAiReply: string;
}

export interface StickerPack {
  id: string;
  name: string;
  icon: string;
  theme: string;
  stickers: ElephantSticker[];
}

export const STICKER_PACKS: StickerPack[] = [
  {
    id: 'pack-1',
    name: '1. ทักทาย & เริ่มงาน',
    icon: '👋',
    theme: 'from-sky-500 to-blue-600',
    stickers: [
      {
        id: 's1-1',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'สวัสดีครับ',
        caption: 'สวัสดีครับ! เริ่มนับสต็อกกันเถอะ 🐘',
        themeColor: 'sky',
        bgGradient: 'from-sky-400 via-blue-500 to-indigo-600',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'namaste',
        propsEmoji: '🙏',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สวัสดีครับ! เริ่มนับสต็อกกันเถอะ',
        defaultAiReply: '### 🐘 สวัสดีครับคุณ Storekeeper!\nยินดีต้อนรับสู่กะการตรวจนับสต็อก OGA Mobile PDA วันนี้ครับ พร้อมให้คำแนะนำทุกขั้นตอน ทั้งการสแกน QR Code 4 รูปแบบ และการตรวจสอบตามมาตรฐาน ISO 9001 ขอให้การตรวจนับวันนี้ราบรื่นและแม่นยำ 100% นะครับ! ✨'
      },
      {
        id: 's1-2',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'พร้อมลุย',
        caption: 'พร้อมลุยงานแล้วครับ! 🔥',
        themeColor: 'orange',
        bgGradient: 'from-orange-400 via-amber-500 to-red-500',
        borderColor: 'border-orange-300',
        textColor: 'text-orange-950',
        badgeColor: 'bg-orange-100 text-orange-800',
        pose: 'thumbsup',
        propsEmoji: '💪',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พร้อมลุยงานแล้วครับ!',
        defaultAiReply: '### 🐘 ยอดเยี่ยมเลยครับ พลังเต็มร้อย!\nอย่าลืมตรวจสอบ **Location ปัจจุบัน** และตรวจสอบว่าโหลด **Master Data** ล่าสุดเข้าเครื่องหรือยังนะครับ หากพร้อมแล้วเริ่มสแกนบาร์โค้ดได้เลยครับ!'
      },
      {
        id: 's1-3',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'กาแฟเช้า',
        caption: 'อรุณสวัสดิ์ยามเช้า ☕',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'coffee',
        propsEmoji: '☕',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: อรุณสวัสดิ์ยามเช้า ดื่มกาแฟเติมพลัง',
        defaultAiReply: '### ☕ อรุณสวัสดิ์ครับ!\nจิบกาแฟอุ่นๆ เติมพลังแล้วเตรียมเครื่อง PDA ให้พร้อมสำหรับการตรวจนับคุณภาพมาตรฐานสากลนะครับ มีคำถามข้อไหนถามผมได้ตลอดเวลาครับ!'
      },
      {
        id: 's1-4',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'ยินดีบริการ',
        caption: 'ยินดีให้บริการครับ 💙',
        themeColor: 'navy',
        bgGradient: 'from-blue-600 via-indigo-700 to-slate-900',
        borderColor: 'border-blue-400',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'bow',
        propsEmoji: '🛡️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยินดีให้บริการครับ',
        defaultAiReply: '### 🐘 AI & ISO Consultant ยินดีช่วยเหลือครับ!\nต้องการสอบถามวิธีสแกน, การตั้งค่า Auto Increment หรือต้องการเอกสาร ISO SOP ฉบับไหน บอกได้เลยครับ'
      },
      {
        id: 's1-5',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'เข้ากะงาน',
        caption: 'เข้ากะทำงานเรียบร้อย 👷',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-rose-600 to-orange-600',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'helmet',
        propsEmoji: '🦺',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: เข้ากะทำงานเรียบร้อย สวมหมวกเซฟตี้',
        defaultAiReply: '### 👷 ปฏิบัติตามมาตรฐานความปลอดภัย 100%!\nบันทึกเวลาเข้ากะตรวจนับสต็อกเรียบร้อย สวมใส่อุปกรณ์ PPE ครบถ้วนตามมาตรฐาน ISO 45001 และพร้อมตรวจนับสต็อกตาม ISO 9001 ครับ!'
      },
      {
        id: 's1-6',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'สต็อกเป๊ะ',
        caption: 'วันนี้สต็อกเป๊ะแน่นอน! ✨',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-indigo-600 to-violet-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'smile',
        propsEmoji: '✨',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: วันนี้สต็อกเป๊ะแน่นอน!',
        defaultAiReply: '### ✨ มั่นใจได้เลยครับ!\nด้วยระบบ **Persistent Location Lock** และการตรวจสอบ Barcode Real-time จาก OGA รับรองว่าผลต่างเป็นศูนย์ (Zero Variance) แน่นอนครับ!'
      },
      {
        id: 's1-7',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'ยินดีต้อนรับ',
        caption: 'ยินดีต้อนรับสู่คลังสินค้า 🏢',
        themeColor: 'sky',
        bgGradient: 'from-cyan-400 via-sky-500 to-blue-600',
        borderColor: 'border-cyan-300',
        textColor: 'text-cyan-950',
        badgeColor: 'bg-cyan-100 text-cyan-800',
        pose: 'open_arms',
        propsEmoji: '🏭',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยินดีต้อนรับสู่คลังสินค้า',
        defaultAiReply: '### 🏢 ยินดีต้อนรับสู่ศูนย์กระจายสินค้า OGA!\nระบบคลังสินค้าพร้อมทำงาน เชื่อมโยงข้อมูลผ่าน Google Sheets และ Cloud Database เรียบร้อยครับ'
      },
      {
        id: 's1-8',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'Start Shift',
        caption: 'Start Shift ลุยเลย! 🚀',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-red-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'rocket',
        propsEmoji: '🚀',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Start Shift ลุยเลย!',
        defaultAiReply: '### 🚀 เริ่มต้นกะตรวจนับอย่างเป็นทางการ!\nระบบพร้อมรับข้อมูลการสแกน หากต้องการคำแนะนำเรื่องการแยกกล่องหรือพาเลทสอบถามได้ทันทีครับ'
      },
      {
        id: 's1-9',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'พลังเต็มร้อย',
        caption: 'พลังเต็มร้อยครับ! ⚡',
        themeColor: 'pink',
        bgGradient: 'from-pink-500 via-fuchsia-600 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'energy',
        propsEmoji: '⚡',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พลังเต็มร้อยครับ!',
        defaultAiReply: '### ⚡ สปีดความเร็วระดับมือโปร!\nเปิดใช้งานฟังก์ชัน **Auto Increment Quantity (+1)** จะช่วยให้ยิงสแกนได้เร็วยิ่งขึ้นกว่าเดิม 3 เท่าเลยครับ!'
      },
      {
        id: 's1-10',
        packId: 'pack-1',
        packName: 'ทักทาย & เริ่มงาน',
        title: 'วันที่ดี',
        caption: 'ขอให้เป็นวันที่ดีครับ 🌸',
        themeColor: 'white',
        bgGradient: 'from-slate-100 via-indigo-50 to-purple-100',
        borderColor: 'border-slate-300',
        textColor: 'text-slate-900',
        badgeColor: 'bg-white text-purple-700 shadow-2xs',
        pose: 'flower',
        propsEmoji: '🌸',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ขอให้เป็นวันที่ดีครับ',
        defaultAiReply: '### 🌸 ขอให้การทำงานวันนี้ราบรื่นและมีความสุขครับ!\nทีม AI OGA พร้อมเคียงข้างช่วยสนับสนุนการตรวจนับของท่านตลอดทั้งวันครับ'
      }
    ]
  },
  {
    id: 'pack-2',
    name: '2. สแกน & ยิงบาร์โค้ด',
    icon: '🔫',
    theme: 'from-red-500 to-orange-500',
    stickers: [
      {
        id: 's2-1',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'ยิงติดทันที',
        caption: 'ยิงบาร์โค้ดแชะเดียวติด! 🔫',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-rose-600 to-orange-500',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'laser_gun',
        propsEmoji: '🎯',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยิงบาร์โค้ดแชะเดียวติด!',
        defaultAiReply: '### 🔫 แม่นยำ รวดเร็ว!\nเครื่อง PDA สแกนบาร์โค้ด 1D/2D ได้อย่างรวดเร็ว ระบบถอดรหัสและดึงข้อมูลจาก Item Master ทันทีในเสี้ยววินาทีครับ'
      },
      {
        id: 's2-2',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'QR 4 แบบ',
        caption: 'สแกน QR Code 4 รูปแบบเป๊ะ 🔲',
        themeColor: 'sky',
        bgGradient: 'from-sky-500 via-blue-600 to-indigo-700',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'qr_scanner',
        propsEmoji: '🔲',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สแกน QR Code 4 รูปแบบเป๊ะ',
        defaultAiReply: '### 🔲 โครงสร้าง QR Code 4 รูปแบบ OGA:\n1. **Single:** `ITEM001`\n2. **Desc/Serial:** `ITEM;DESC;SERIAL`\n3. **Full 4 Fields:** `ITEM,LOT,EXP,QTY`\n4. **Item + Lot:** `ITEM,LOT`\nระบบแยกฟิลด์และบันทึกอัตโนมัติถูกต้องตามมาตรฐานครับ!'
      },
      {
        id: 's2-3',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'Auto +1',
        caption: 'Auto +1 ยิงรัวๆ ไม่ต้องกด! ➕',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-violet-600 to-indigo-600',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'auto_plus',
        propsEmoji: '➕',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Auto +1 ยิงรัวๆ ไม่ต้องกด!',
        defaultAiReply: '### ➕ Auto Increment Mode Active!\nทุกครั้งที่ยิงบาร์โค้ดเดิมซ้ำ ระบบจะบวกจำนวนนับเพิ่มทีละ +1 โดยอัตโนมัติ ช่วยลดเวลาการทำงานได้มากกว่า 60% ครับ!'
      },
      {
        id: 's2-4',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'กล้อง AI',
        caption: 'วิเคราะห์ฉลากผ่าน AI 📸',
        themeColor: 'orange',
        bgGradient: 'from-orange-400 via-amber-500 to-yellow-500',
        borderColor: 'border-orange-300',
        textColor: 'text-orange-950',
        badgeColor: 'bg-orange-100 text-orange-800',
        pose: 'camera_ai',
        propsEmoji: '📸',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: วิเคราะห์ฉลากผ่าน AI',
        defaultAiReply: '### 📸 AI Vision Analysis พร้อมทำงาน!\nถ่ายภาพฉลากสินค้าที่บาร์โค้ดเลือนหรือฉีกขาด ส่งเข้ามาในแชทนี้ได้เลย AI จะช่วยอ่านข้อความและระบุรหัสสินค้าให้ทันทีครับ'
      },
      {
        id: 's2-5',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'สำเร็จ 100%',
        caption: 'สแกนสำเร็จ 100% 🟢',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'check_success',
        propsEmoji: '✅',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สแกนสำเร็จ 100%',
        defaultAiReply: '### ✅ ข้อมูลถูกต้องครบถ้วน!\nบันทึกรหัสสินค้า, วันที่, เวลา, และ Device ID เข้าสู่ Log การตรวจนับเรียบร้อยแล้วครับ'
      },
      {
        id: 's2-6',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'เรดาร์ตรวจจับ',
        caption: 'ตรวจพบบาร์โค้ดแล้ว! 🔍',
        themeColor: 'red',
        bgGradient: 'from-rose-500 via-red-600 to-orange-600',
        borderColor: 'border-rose-300',
        textColor: 'text-rose-950',
        badgeColor: 'bg-rose-100 text-rose-800',
        pose: 'radar_glasses',
        propsEmoji: '🔍',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ตรวจพบบาร์โค้ดแล้ว!',
        defaultAiReply: '### 🔍 ตรวจพบบาร์โค้ดในระยะโฟกัส!\nหัวอ่านเลเซอร์จับสัญญาณบาร์โค้ดได้คมชัด พร้อมบันทึกจำนวนนับครับ'
      },
      {
        id: 's2-7',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'Auto Select',
        caption: 'Auto Select พร้อมยิงต่อ ⚡',
        themeColor: 'pink',
        bgGradient: 'from-pink-500 via-rose-500 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'fast_tap',
        propsEmoji: '⚡',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Auto Select พร้อมยิงต่อ',
        defaultAiReply: '### ⚡ Auto Highlight & Focus!\nระบบเลือกข้อความในช่อง Barcode อัตโนมัติ ยิงตัวถัดไปได้ทันทีโดยไม่ต้องแตะหน้าจอลบข้อความเดิมครับ'
      },
      {
        id: 's2-8',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'ตรงเป้าหมาย',
        caption: 'ยิงตรงเป้าหมาย 🎯',
        themeColor: 'sky',
        bgGradient: 'from-sky-400 via-blue-500 to-indigo-600',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'target_bullseye',
        propsEmoji: '🎯',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยิงตรงเป้าหมาย',
        defaultAiReply: '### 🎯 แม่นยำระดับมิลลิเมตร!\nการอ่านค่าบาร์โค้ดรวดเร็วและไม่มีสัญญาณรบกวน เหมาะสำหรับการนับสต็อกแบบ High-density Warehouse ครับ'
      },
      {
        id: 's2-9',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'ครบทุกฟิลด์',
        caption: 'อ่านข้อมูล ครบทุกฟิลด์ 📋',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-red-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'holding_qr',
        propsEmoji: '📊',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: อ่านข้อมูล ครบทุกฟิลด์',
        defaultAiReply: '### 📋 ข้อมูลครบถ้วนทั้ง 4 มิติ!\nItem Code, Lot No, Expiry Date, และ Serial Number ถูกจัดเก็บลงฐานข้อมูลอย่างเป็นระเบียบครับ'
      },
      {
        id: 's2-10',
        packId: 'pack-2',
        packName: 'สแกน & ยิงบาร์โค้ด',
        title: 'สปีดเทพ',
        caption: 'สปีดยิงระดับเทพ! 🏆',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-violet-600 to-indigo-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'champion_speed',
        propsEmoji: '⚡',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สปีดยิงระดับเทพ!',
        defaultAiReply: '### 🏆 ยิงไวกว่า 120 ชิ้นต่อนาที!\nสถิติการสแกนยอดเยี่ยมมากครับ อย่าลืมตรวจเช็คความถูกต้องของ Lot และ Exp Date เป็นระยะด้วยนะครับ'
      }
    ]
  },
  {
    id: 'pack-3',
    name: '3. Location & ล็อกโซน',
    icon: '📍',
    theme: 'from-indigo-600 to-blue-700',
    stickers: [
      {
        id: 's3-1',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'ล็อก Location',
        caption: 'ล็อก Location เรียบร้อย! 📍',
        themeColor: 'red',
        bgGradient: 'from-rose-500 via-red-600 to-orange-600',
        borderColor: 'border-rose-300',
        textColor: 'text-rose-950',
        badgeColor: 'bg-rose-100 text-rose-800',
        pose: 'pin_location',
        propsEmoji: '📍',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ล็อก Location เรียบร้อย!',
        defaultAiReply: '### 📍 Persistent Location Lock ทำงาน!\nระบบล็อก Location ไว้ให้คุณตลอดการสแกน ทุกชิ้นที่ยิงจะถูกบันทึกลง Location นี้โดยไม่ต้องพิมพ์ซ้ำครับ'
      },
      {
        id: 's3-2',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'โซน Rack A-01',
        caption: 'กำลังนับโซน Rack A-01 📦',
        themeColor: 'sky',
        bgGradient: 'from-sky-400 via-blue-500 to-indigo-600',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'rack_counting',
        propsEmoji: '🏢',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: กำลังนับโซน Rack A-01',
        defaultAiReply: '### 📦 ตรวจนับตามผัง Location A-01!\nเริ่มนับจากชั้นล่างขึ้นชั้นบน และนับจากซ้ายไปขวาตามมาตรฐาน ISO Work Instruction นะครับ'
      },
      {
        id: 's3-3',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'ย้ายโซนถัดไป',
        caption: 'ย้ายนับโซนถัดไป 🚜',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-red-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'forklift_driving',
        propsEmoji: '🚜',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ย้ายนับโซนถัดไป ขับโฟล์คลิฟต์',
        defaultAiReply: '### 🚜 เปลี่ยน Location ใหม่:\nสแกนบาร์โค้ดป้าย Location ประจำชั้นวางใหม่ เพื่อให้ระบบเปลี่ยน Location Lock ทันทีครับ!'
      },
      {
        id: 's3-4',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'ผังคลังสินค้า',
        caption: 'ตรวจตามผัง Warehouse 🗺️',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-indigo-600 to-blue-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'warehouse_map',
        propsEmoji: '🗺️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ตรวจตามผัง Warehouse',
        defaultAiReply: '### 🗺️ แผนผังคลังสินค้ามาตรฐาน:\nครอบคลุมทั้ง Zone A (Fast Moving), Zone B (Medium), Zone C (Slow Moving) และ Cold Storage ครับ'
      },
      {
        id: 's3-5',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'ห้ามลืมเปลี่ยน',
        caption: 'ห้ามลืมเปลี่ยน Location! ⚠️',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-red-500',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'reminder_sign',
        propsEmoji: '⚠️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ห้ามลืมเปลี่ยน Location!',
        defaultAiReply: '### ⚠️ ข้อควรระวังสำคัญ (Quality Alert):\nเมื่อเดินเปลี่ยนชั้นวางหรือแถว ต้องสแกน Location ใหม่ทุกครั้งเพื่อป้องกันสต็อกคลาดเคลื่อนข้ามช่องจัดเก็บครับ'
      },
      {
        id: 's3-6',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'ชั้นวางนับครบ',
        caption: 'ชั้นวางนี้ตรวจนับครบแล้ว 🟢',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'shelf_complete',
        propsEmoji: '✅',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ชั้นวางนี้ตรวจนับครบแล้ว',
        defaultAiReply: '### ✅ ชั้นวางตรวจนับครบ 100%!\nทำการติดสติกเกอร์ **"COUNTED / ตรวจนับแล้ว"** ที่ป้ายหน้าชั้นเพื่อเป็นหลักฐานเชิงประจักษ์ตาม ISO ครับ'
      },
      {
        id: 's3-7',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'กุญแจล็อก',
        caption: 'Persistent Location Lock 🔒',
        themeColor: 'red',
        bgGradient: 'from-red-600 via-rose-600 to-amber-600',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'padlock',
        propsEmoji: '🔒',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Persistent Location Lock',
        defaultAiReply: '### 🔒 ความแม่นยำระดับสูงสุด:\nแม้จะออกจากหน้าจอแล้วเปิดกลับมาใหม่ Location ที่คุณตั้งไว้จะไม่สูญหาย มั่นใจได้ในความปลอดภัยของข้อมูลครับ'
      },
      {
        id: 's3-8',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'ชั้นบนสุด',
        caption: 'ตรวจนับชั้นบนสุดเรียบร้อย 🪜',
        themeColor: 'sky',
        bgGradient: 'from-cyan-400 via-sky-500 to-blue-600',
        borderColor: 'border-cyan-300',
        textColor: 'text-cyan-950',
        badgeColor: 'bg-cyan-100 text-cyan-800',
        pose: 'ladder_top',
        propsEmoji: '🪜',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ตรวจนับชั้นบนสุดเรียบร้อย',
        defaultAiReply: '### 🪜 ความปลอดภัยและการตรวจนับสมบูรณ์:\nตรวจนับชั้นสูง (High-bay Rack) เสร็จสิ้นอย่างปลอดภัย ยอดสินค้าชั้นบนตรงตามบันทึกครับ'
      },
      {
        id: 's3-9',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'เฝ้าประตูคลัง',
        caption: 'โซนนี้ผ่านการตรวจสอบแล้ว 🛡️',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-indigo-700 to-slate-900',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'guard_door',
        propsEmoji: '🛡️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: โซนนี้ผ่านการตรวจสอบแล้ว',
        defaultAiReply: '### 🛡️ ควบคุมพื้นที่จัดเก็บมาตรฐาน:\nโซนสินค้าผ่านการตรวจสอบพร้อมเปิดให้เบิก-จ่ายตามคำสั่งซื้อ (Sales Order) ได้ตามปกติครับ'
      },
      {
        id: 's3-10',
        packId: 'pack-3',
        packName: 'Location & ล็อกโซน',
        title: 'เคลียร์โซน',
        caption: 'เคลียร์โซน 100% 🚩',
        themeColor: 'white',
        bgGradient: 'from-slate-100 via-emerald-50 to-teal-100',
        borderColor: 'border-emerald-300',
        textColor: 'text-emerald-950',
        badgeColor: 'bg-emerald-100 text-emerald-800',
        pose: 'flag_green',
        propsEmoji: '🚩',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: เคลียร์โซน 100%',
        defaultAiReply: '### 🚩 สรุปผลการตรวจนับโซน:\nรายการสินค้าทุก SKU ในโซนนี้ถูกตรวจนับและส่งยอดเข้าระบบครบถ้วนสมบูรณ์แบบครับ!'
      }
    ]
  },
  {
    id: 'pack-4',
    name: '4. ยอดตรง & นับถูกต้อง',
    icon: '👍',
    theme: 'from-emerald-500 to-teal-600',
    stickers: [
      {
        id: 's4-1',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'ยอดตรง 100%',
        caption: 'ยอดตรงเป๊ะ 100%! 👍',
        themeColor: 'sky',
        bgGradient: 'from-emerald-400 via-teal-500 to-cyan-600',
        borderColor: 'border-emerald-300',
        textColor: 'text-emerald-950',
        badgeColor: 'bg-emerald-100 text-emerald-800',
        pose: 'double_thumbsup',
        propsEmoji: '👍',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยอดตรงเป๊ะ 100%!',
        defaultAiReply: '### 👍 100% Inventory Accuracy!\nความแม่นยำของยอดสินค้าคงคลังบรรลุเป้าหมาย KPI ตามมาตรฐาน ISO 9001:2015 ยอดเยี่ยมมากครับ!'
      },
      {
        id: 's4-2',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'สมดุลสต็อก',
        caption: 'Balance Stock สมบูรณ์แบบ ⚖️',
        themeColor: 'navy',
        bgGradient: 'from-blue-600 via-indigo-700 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'scales_balance',
        propsEmoji: '⚖️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Balance Stock สมบูรณ์แบบ',
        defaultAiReply: '### ⚖️ ยอดสต็อกทางกายภาพ = ยอดในระบบ:\nPhysical Count เท่ากับ Book Balance พอดิบพอดี ไม่มีผลต่าง Stock Discrepancy ครับ'
      },
      {
        id: 's4-3',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'เหรียญทอง',
        caption: 'ตรวจนับแม่นยำ ไร้ข้อผิดพลาด 🥇',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-yellow-500 to-orange-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'gold_medal',
        propsEmoji: '🥇',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ตรวจนับแม่นยำ ไร้ข้อผิดพลาด',
        defaultAiReply: '### 🥇 มอบเหรียญทองความเป๊ะ!\nขอชื่นชมทีม Storekeeper ที่ปฏิบัติงานอย่างละเอียดรอบคอบตามข้อกำหนดการตรวจนับครับ'
      },
      {
        id: 's4-4',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'คำนวณถูกต้อง',
        caption: 'คำนวณยอดถูกต้อง 🔢',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-indigo-600 to-violet-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'calculator',
        propsEmoji: '🔢',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: คำนวณยอดถูกต้อง',
        defaultAiReply: '### 🔢 รวมจำนวนชิ้น, กล่อง และพาเลทถูกต้อง:\nระบบสูตรคำนวณอัตโนมัติช่วยลด Human Error ได้ 100% มั่นใจได้ในผลลัพธ์ครับ'
      },
      {
        id: 's4-5',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'สต็อกน่ารัก',
        caption: 'สต็อกเป๊ะ น่ารักที่สุด 💖',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-purple-500',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'heart_hands',
        propsEmoji: '💖',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สต็อกเป๊ะ น่ารักที่สุด',
        defaultAiReply: '### 💖 ขอบคุณในความตั้งใจครับ!\nสต็อกที่เรียบร้อยทำให้ฝ่ายจัดส่งและฝ่ายขายทำงานได้อย่างมั่นใจ ไร้ปัญหาสินค้าขาดมือครับ'
      },
      {
        id: 's4-6',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'Audit Pass',
        caption: 'Audit Pass ผ่านฉลุย! ✅',
        themeColor: 'sky',
        bgGradient: 'from-cyan-400 via-sky-500 to-blue-600',
        borderColor: 'border-cyan-300',
        textColor: 'text-cyan-950',
        badgeColor: 'bg-cyan-100 text-cyan-800',
        pose: 'pass_stamp',
        propsEmoji: '✅',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Audit Pass ผ่านฉลุย!',
        defaultAiReply: '### ✅ ผู้ตรวจสอบภายใน (Auditor) รับรองผล:\nผ่านการประเมินการสุ่มตรวจนับสต็อก (Cycle Count Audit) ตามมาตรฐานสากลครับ'
      },
      {
        id: 's4-7',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'ปรบมือรัวๆ',
        caption: 'ยอดตรงตาม Master Data 👏',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-red-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'clapping',
        propsEmoji: '👏',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยอดตรงตาม Master Data',
        defaultAiReply: '### 👏 ปรบมือให้กับความสำเร็จ!\nข้อมูลตรงกับ Master Data ทุกตัวอักษร ไม่มี SKU แปลกปลอมหลุดรอดเข้ามาครับ'
      },
      {
        id: 's4-8',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'คลังดีเด่น',
        caption: 'คลังสินค้าดีเด่นประจำวัน 🏆',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'shield_award',
        propsEmoji: '🏆',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: คลังสินค้าดีเด่นประจำวัน',
        defaultAiReply: '### 🏆 Best Warehouse Performance!\nผลงานการตรวจนับวันนี้มีประสิทธิภาพสูงและรวดเร็วเป็นอันดับต้นๆ ของสาขาครับ'
      },
      {
        id: 's4-9',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'Variance 0',
        caption: 'ไม่มีผลต่าง (Variance 0) 🎉',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-violet-600 to-indigo-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'zero_diff',
        propsEmoji: '🎉',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ไม่มีผลต่าง (Variance 0)',
        defaultAiReply: '### 🎉 Zero Stock Discrepancy:\nผลต่าง Diff = 0 ชิ้น ไม่ต้องทำใบปรับยอดสต็อก (Stock Adjustment) ให้ยุ่งยากครับ!'
      },
      {
        id: 's4-10',
        packId: 'pack-4',
        packName: 'ยอดตรง & นับถูกต้อง',
        title: 'ระเบิดพลุ',
        caption: 'ปิดจ๊อบยอดตรงเป๊ะ! 🎆',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-orange-500 to-yellow-400',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'fireworks',
        propsEmoji: '🎆',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ปิดจ๊อบยอดตรงเป๊ะ!',
        defaultAiReply: '### 🎆 ฉลองความสำเร็จปิดงานตรวจนับ!\nส่งออกไฟล์สรุปยอด หรือพิมพ์เอกสารใบรับรองผลตรวจนับได้จากเมนูด้านล่างเลยครับ'
      }
    ]
  },
  {
    id: 'pack-5',
    name: '5. แจ้งเตือน & ของชำรุด',
    icon: '⚠️',
    theme: 'from-rose-500 to-red-600',
    stickers: [
      {
        id: 's5-1',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'พบของชำรุด',
        caption: 'พบสินค้าชำรุด! กักกันด่วน ⚠️',
        themeColor: 'red',
        bgGradient: 'from-red-600 via-rose-700 to-amber-600',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'warning_sign',
        propsEmoji: '⚠️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พบสินค้าชำรุด! กักกันด่วน',
        defaultAiReply: '### ⚠️ การจัดการสินค้าชำรุดตาม ISO 9001 (Clause 8.7):\n1. **คัดแยกทันที:** นำออกจากชั้นวางปกติ ย้ายไปยังโซน **Quarantine / Damage Area**\n2. **ติดป้ายสถานะ:** ติดแท็กสีแดง "Non-conforming / รอตัดจำหน่าย"\n3. **บันทึกในระบบ:** เลือกบันทึกสถานะเป็น `DAMAGE` ในหน้าสแกน OGA PDA\n4. **รายงาน:** แจ้งหัวหน้างานเพื่อออกใบ NCR ต่อไปครับ'
      },
      {
        id: 's5-2',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'ยอดไม่ตรง',
        caption: 'ยอดนับไม่ตรงกับระบบ! 😲',
        themeColor: 'orange',
        bgGradient: 'from-amber-500 via-orange-600 to-red-600',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'shocked',
        propsEmoji: '😲',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยอดนับไม่ตรงกับระบบ!',
        defaultAiReply: '### 😲 ขั้นตอนการตรวจนับซ้ำ (Recount Procedure):\n1. ตรวจสอบว่ามีสินค้าซ่อนอยู่ด้านหลังชั้นวางหรือไม่\n2. ตรวจสอบว่ามีการหยิบสลับ SKU ใกล้เคียงหรือไม่\n3. ทำการ Double Count โดยผู้ตรวจนับคนที่สองเพื่อยืนยันยอดจริงครับ'
      },
      {
        id: 's5-3',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'กล่องบุบ',
        caption: 'บรรจุภัณฑ์เสียหาย (Damage) 📦',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-pink-600 to-rose-600',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'crushed_box',
        propsEmoji: '📦',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: บรรจุภัณฑ์เสียหาย กล่องบุบ',
        defaultAiReply: '### 📦 กล่องบุบ/ฉีกขาด:\nถ่ายภาพส่งเข้ามาในแชทนี้เพื่อบันทึกหลักฐาน หากสินค้าภายในไม่เสียหาย ให้เปลี่ยนกล่องบรรจุใหม่และติดบาร์โค้ดเดิมครับ'
      },
      {
        id: 's5-4',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'สินค้าหมดอายุ',
        caption: 'สินค้าหมดอายุ (Exp Date) ⌛',
        themeColor: 'red',
        bgGradient: 'from-rose-600 via-red-700 to-purple-800',
        borderColor: 'border-rose-300',
        textColor: 'text-rose-950',
        badgeColor: 'bg-rose-100 text-rose-800',
        pose: 'hourglass_expired',
        propsEmoji: '⌛',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สินค้าหมดอายุ Exp Date',
        defaultAiReply: '### ⌛ FEFO Control Alert:\nสินค้าเกินกำหนดอายุการจัดเก็บ (Expired) ห้ามนำจ่ายเด็ดขาด! บันทึกลงใบรายงานของหมดอายุเพื่อส่งทำลายตามกระบวนการ ISO ครับ'
      },
      {
        id: 's5-5',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'โทรโข่งเตือน',
        caption: 'แจ้งเตือนหัวหน้างานทันที 📢',
        themeColor: 'orange',
        bgGradient: 'from-orange-500 via-amber-600 to-yellow-500',
        borderColor: 'border-orange-300',
        textColor: 'text-orange-950',
        badgeColor: 'bg-orange-100 text-orange-800',
        pose: 'megaphone',
        propsEmoji: '📢',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: แจ้งเตือนหัวหน้างานทันที',
        defaultAiReply: '### 📢 ส่งสัญญาณแจ้งเตือน Supervisor:\nระบบจะแนบรายงานผลต่างและภาพถ่ายส่งต่อไปยังหน้าแดชบอร์ดของผู้จัดการคลังสินค้าทันทีครับ'
      },
      {
        id: 's5-6',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'ห้ามย้าย Non-con',
        caption: 'ติดป้ายห้ามย้าย Non-conformance 🚫',
        themeColor: 'red',
        bgGradient: 'from-red-600 via-rose-600 to-red-800',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'danger_tape',
        propsEmoji: '🚫',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ติดป้ายห้ามย้าย Non-conformance',
        defaultAiReply: '### 🚫 ติดแถบกั้นพื้นที่ Non-conforming Product:\nป้องกันการหยิบผิดพลาดตามข้อกำหนดมาตรฐานคุณภาพ ISO 9001 ข้อ 8.7 อย่างเคร่งครัดครับ'
      },
      {
        id: 's5-7',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'Out of Master',
        caption: 'สินค้า Out of Master Data! ❓',
        themeColor: 'sky',
        bgGradient: 'from-sky-500 via-blue-600 to-indigo-700',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'sweat_confused',
        propsEmoji: '❓',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สินค้า Out of Master Data!',
        defaultAiReply: '### ❓ บาร์โค้ดไม่อยู่ในฐานข้อมูล:\n1. ตรวจสอบการตั้งค่า **Confirm Out-of-Master Prompt** ในหน้า Settings\n2. อัปเดตไฟล์ Master Data ล่าสุดจาก Server หรือ Google Sheets ครับ'
      },
      {
        id: 's5-8',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'STOP ตรวจนับ',
        caption: 'หยุดตรวจนับเพื่อ Re-check 🛑',
        themeColor: 'red',
        bgGradient: 'from-red-700 via-rose-800 to-red-900',
        borderColor: 'border-red-400',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-900',
        pose: 'stop_sign',
        propsEmoji: '🛑',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: หยุดตรวจนับเพื่อ Re-check',
        defaultAiReply: '### 🛑 หยุดชั่วคราวเพื่อตรวจสอบความถูกต้อง:\nหยุดการสแกนในโซนนี้ชั่วคราว ดึงข้อมูลการเคลื่อนไหวย้อนหลัง (Movement Log) มาเปรียบเทียบก่อนครับ'
      },
      {
        id: 's5-9',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'ถ่ายหลักฐาน',
        caption: 'ถ่ายรูปหลักฐานความเสียหาย 📷',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'evidence_camera',
        propsEmoji: '📷',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ถ่ายรูปหลักฐานความเสียหาย',
        defaultAiReply: '### 📷 ถ่ายภาพความเสียหาย:\nใช้ปุ่มกล้อง AI ถ่ายรูปจุดที่ชำรุด ระบบจะเก็บภาพพร้อมเวลาและพิกัดไว้ในรายงาน Audit ครับ'
      },
      {
        id: 's5-10',
        packId: 'pack-5',
        packName: 'แจ้งเตือน & ของชำรุด',
        title: 'ออกใบ NCR',
        caption: 'ออกเอกสาร NCR ชำรุดเรียบร้อย 📝',
        themeColor: 'pink',
        bgGradient: 'from-pink-500 via-rose-600 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'ncr_form',
        propsEmoji: '📝',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ออกเอกสาร NCR ชำรุดเรียบร้อย',
        defaultAiReply: '### 📝 ออกเอกสาร NCR (Non-Conformance Report) สมบูรณ์:\nระบุสาเหตุ, ผู้รับผิดชอบ และแนวทางแก้ไขป้องกัน (CAPA) ตามมาตรฐาน ISO 9001 เรียบร้อยครับ'
      }
    ]
  },
  {
    id: 'pack-6',
    name: '6. มาตรฐาน ISO & เอกสาร',
    icon: '🛡️',
    theme: 'from-blue-600 to-indigo-800',
    stickers: [
      {
        id: 's6-1',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'ISO 9001',
        caption: 'มาตรฐาน ISO 9001 รับรอง! 🛡️',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'iso_shield',
        propsEmoji: '🛡️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: มาตรฐาน ISO 9001 รับรอง!',
        defaultAiReply: '### 🛡️ ISO 9001:2015 Quality Management System:\nกระบวนการตรวจนับสต็อกสินค้าของ OGA ออกแบบตามมาตรฐานการบริหารคุณภาพ สอดคล้องตามข้อกำหนด 8.5 และ 8.7 ครับ!'
      },
      {
        id: 's6-2',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'ตาม SOP เป๊ะ',
        caption: 'ปฏิบัติงานตาม SOP ถูกต้อง 📑',
        themeColor: 'sky',
        bgGradient: 'from-sky-400 via-blue-500 to-indigo-600',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'sop_folder',
        propsEmoji: '📑',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ปฏิบัติงานตาม SOP ถูกต้อง',
        defaultAiReply: '### 📑 Standard Operating Procedure (SOP-WH-001):\nปฏิบัติตาม Work Instruction ทุกขั้นตอน ช่วยรักษาคุณภาพการทำงานให้เป็นมาตรฐานเดียวกันทุกกะครับ'
      },
      {
        id: 's6-3',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'Checklist ครบ',
        caption: 'Audit Checklist ครบทุกข้อ 📝',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-violet-600 to-indigo-600',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'checklist_done',
        propsEmoji: '📝',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Audit Checklist ครบทุกข้อ',
        defaultAiReply: '### 📝 ตรวจสอบผ่านเกณฑ์ทุกข้อ:\n- การล็อก Location ✔️\n- การตรวจสอบ QR Code ✔️\n- การตรวจอายุสินค้า ✔️\n- การบันทึก Device ID ✔️'
      },
      {
        id: 's6-4',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'ISO 27001',
        caption: 'ความปลอดภัยข้อมูล ISO 27001 🔒',
        themeColor: 'navy',
        bgGradient: 'from-indigo-700 via-slate-800 to-blue-900',
        borderColor: 'border-indigo-400',
        textColor: 'text-indigo-950',
        badgeColor: 'bg-indigo-100 text-indigo-900',
        pose: 'data_security',
        propsEmoji: '🔒',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ความปลอดภัยข้อมูล ISO 27001',
        defaultAiReply: '### 🔒 ISO/IEC 27001 Information Security:\nข้อมูลสต็อกและรหัสผ่านถูกเข้ารหัส (Encrypted) ปลอดภัยต่อการเข้าถึงโดยไม่ได้รับอนุญาต 100% ครับ'
      },
      {
        id: 's6-5',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'อนุมัติผลนับ',
        caption: 'อนุมัติผลการตรวจนับแล้ว ✍️',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-red-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'sign_approval',
        propsEmoji: '✍️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: อนุมัติผลการตรวจนับแล้ว',
        defaultAiReply: '### ✍️ ผ่านการลงนามอนุมัติ:\nผู้จัดการคลังสินค้าลงนามรับรองผลการตรวจนับเรียบร้อย พร้อมส่งต่อฝ่ายบัญชีเพื่อปิดงบสต็อกครับ'
      },
      {
        id: 's6-6',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'Doc Rev.03',
        caption: 'Document Control Rev.03 📄',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'document_control',
        propsEmoji: '📄',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Document Control Rev.03',
        defaultAiReply: '### 📄 เอกสารควบคุมฉบับล่าสุด:\nรหัสเอกสาร `SOP-WH-COUNT-001 (Rev.03)` มีผลบังคับใช้ครอบคลุมทุกคลังสินค้า OGA International ครับ'
      },
      {
        id: 's6-7',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'Internal Audit',
        caption: 'Internal Audit เรียบร้อย 🧐',
        themeColor: 'sky',
        bgGradient: 'from-cyan-400 via-sky-500 to-blue-600',
        borderColor: 'border-cyan-300',
        textColor: 'text-cyan-950',
        badgeColor: 'bg-cyan-100 text-cyan-800',
        pose: 'auditor_inspect',
        propsEmoji: '🧐',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Internal Audit เรียบร้อย',
        defaultAiReply: '### 🧐 ผลการตรวจประเมินภายใน:\nไม่มีข้อบกพร่องระดับ CAR (Corrective Action Request) มีเพียงข้อเสนอแนะเพื่อการปรับปรุงอย่างต่อเนื่อง (OFI) ครับ'
      },
      {
        id: 's6-8',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'พร้อมรับตรวจ',
        caption: 'พร้อมรับการตรวจ ISO 👔',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-indigo-700 to-slate-900',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'formal_tie',
        propsEmoji: '👔',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พร้อมรับการตรวจ ISO',
        defaultAiReply: '### 👔 เอกสารและหลักฐานพร้อม 100%:\nสามารถกดปุ่ม "Export เอกสาร ISO" ด้านล่างเพื่อเตรียมเอกสาร Word/PDF สำหรับแสดงต่อ Auditor ได้ทันทีครับ'
      },
      {
        id: 's6-9',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'OGA Quality',
        caption: 'OGA Standardized Quality 🌟',
        themeColor: 'orange',
        bgGradient: 'from-orange-500 via-amber-500 to-blue-700',
        borderColor: 'border-orange-300',
        textColor: 'text-orange-950',
        badgeColor: 'bg-orange-100 text-orange-800',
        pose: 'quality_star',
        propsEmoji: '🌟',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: OGA Standardized Quality',
        defaultAiReply: '### 🌟 มาตรฐานระดับสากลโดย OGA:\nมุ่งมั่นพัฒนาระบบ Auto-ID และ Barcode เพื่อคุณภาพคลังสินค้าที่ดีที่สุดครับ'
      },
      {
        id: 's6-10',
        packId: 'pack-6',
        packName: 'มาตรฐาน ISO & เอกสาร',
        title: 'Certificate',
        caption: 'ผ่านการประเมินคุณภาพ ISO 🏆',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-amber-500 to-yellow-400',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'certificate_award',
        propsEmoji: '🏆',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ผ่านการประเมินคุณภาพ ISO Certificate',
        defaultAiReply: '### 🏆 Certificate of Compliance:\nการันตีความถูกต้องของข้อมูลสต็อกสินค้าตามมาตรฐานสากลระดับโลกครับ!'
      }
    ]
  },
  {
    id: 'pack-7',
    name: '7. Cloud & ซิงค์ Google Sheets',
    icon: '☁️',
    theme: 'from-sky-400 to-teal-500',
    stickers: [
      {
        id: 's7-1',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'ซิงค์ Sheets แล้ว',
        caption: 'ซิงค์ขึ้น Google Sheets แล้ว! ☁️',
        themeColor: 'sky',
        bgGradient: 'from-sky-400 via-cyan-500 to-blue-600',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'cloud_sync',
        propsEmoji: '☁️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ซิงค์ขึ้น Google Sheets แล้ว!',
        defaultAiReply: '### ☁️ ข้อมูลถูกส่งเข้า Google Sheets เรียบร้อย:\nยอดตรวจนับถูกบันทึกลง Sheet `ScannedStock` แบบ Real-time พร้อมเปิดดูบนบราวเซอร์หรือมือถือได้ทันทีครับ!'
      },
      {
        id: 's7-2',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'Upload สำเร็จ',
        caption: 'Upload ข้อมูลเรียบร้อย ⬆️',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-red-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'upload_arrow',
        propsEmoji: '⬆️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Upload ข้อมูลเรียบร้อย',
        defaultAiReply: '### ⬆️ การส่งข้อมูล (Data Upload) เสร็จสมบูรณ์:\nไม่มีข้อมูลค้างในเครื่อง (0 Pending Records) ข้อมูลถูกจัดเก็บอย่างปลอดภัยบนคลาวด์ครับ'
      },
      {
        id: 's7-3',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'บันทึก Database',
        caption: 'บันทึกลงฐานข้อมูลสำเร็จ 💾',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'save_disk',
        propsEmoji: '💾',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: บันทึกลงฐานข้อมูลสำเร็จ',
        defaultAiReply: '### 💾 Database Commit Success:\nสร้าง Transaction Log พร้อม Timestamp ป้องกันข้อมูลสูญหาย 100% ครับ'
      },
      {
        id: 's7-4',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'ส่งอีเมลสรุป',
        caption: 'ส่งรายงานสรุปยอดนับแล้ว ✉️',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-indigo-600 to-violet-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'email_sent',
        propsEmoji: '✉️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ส่งรายงานสรุปยอดนับแล้ว',
        defaultAiReply: '### ✉️ Email Report Dispatched:\nส่งสรุปผลการตรวจนับรายวันไปยังทีมบริหารและแผนกที่เกี่ยวข้องเรียบร้อยครับ'
      },
      {
        id: 's7-5',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'Sheets อัปเดตสด',
        caption: 'ตาราง Google Sheets อัปเดตสด 📊',
        themeColor: 'sky',
        bgGradient: 'from-emerald-400 via-teal-500 to-sky-600',
        borderColor: 'border-emerald-300',
        textColor: 'text-emerald-950',
        badgeColor: 'bg-emerald-100 text-emerald-800',
        pose: 'sheets_table',
        propsEmoji: '📊',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ตาราง Google Sheets อัปเดตสด',
        defaultAiReply: '### 📊 Live Google Sheets Dashboard:\nกราฟและ Pivot Table บน Google Sheets รีเฟรชข้อมูลตามยอดนับล่าสุดทันทีครับ'
      },
      {
        id: 's7-6',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'สัญญาณเต็ม 100',
        caption: 'สัญญาณ PDA ออนไลน์ 100% 📶',
        themeColor: 'navy',
        bgGradient: 'from-blue-600 via-sky-600 to-indigo-700',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'wifi_signal',
        propsEmoji: '📶',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สัญญาณ PDA ออนไลน์ 100%',
        defaultAiReply: '### 📶 การเชื่อมต่ออินเทอร์เน็ตเสถียร:\nWi-Fi คลื่น 5GHz แรงเต็มขีด หมดกังวลเรื่องการหลุดสัญญาณระหว่างเดินนับในคลังครับ'
      },
      {
        id: 's7-7',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'Cloud Gateway',
        caption: 'Connected to Cloud Server ⚡',
        themeColor: 'orange',
        bgGradient: 'from-orange-500 via-amber-500 to-red-500',
        borderColor: 'border-orange-300',
        textColor: 'text-orange-950',
        badgeColor: 'bg-orange-100 text-orange-800',
        pose: 'cloud_gateway',
        propsEmoji: '⚡',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Connected to Cloud Server',
        defaultAiReply: '### ⚡ Google Apps Script Webhook พร้อมทำงาน:\nรับ-ส่งข้อมูลด้วยความเร็วสูงผ่าน Secure HTTPS API Gateway ครับ'
      },
      {
        id: 's7-8',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'โหลด Master',
        caption: 'โหลด Master Data ล่าสุดแล้ว 📥',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'download_master',
        propsEmoji: '📥',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: โหลด Master Data ล่าสุดแล้ว',
        defaultAiReply: '### 📥 Master Data Synchronized:\nอัปเดตรายชื่อสินค้าและ Location ล่าสุดพร้อมใช้งานแบบ Offline ในเครื่องเรียบร้อยครับ'
      },
      {
        id: 's7-9',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'Export สำเร็จ',
        caption: 'Export ไฟล์ Excel/CSV สำเร็จ 📄',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-rose-600 to-orange-500',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'export_csv',
        propsEmoji: '📄',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Export ไฟล์ Excel/CSV สำเร็จ',
        defaultAiReply: '### 📄 ส่งออกไฟล์เรียบร้อย:\nไฟล์ถูกสร้างพร้อมเปิดใช้งานในโปรแกรม Excel หรือนำเข้าโปรแกรม ERP ได้ทันทีครับ'
      },
      {
        id: 's7-10',
        packId: 'pack-7',
        packName: 'Cloud & ซิงค์ Google Sheets',
        title: 'Sync Done',
        caption: 'Real-time Sync Done! ✔️',
        themeColor: 'white',
        bgGradient: 'from-slate-100 via-sky-50 to-emerald-100',
        borderColor: 'border-sky-300',
        textColor: 'text-slate-900',
        badgeColor: 'bg-emerald-100 text-emerald-800 font-bold',
        pose: 'sync_done',
        propsEmoji: '✔️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: Real-time Sync Done!',
        defaultAiReply: '### ✔️ ซิงค์ข้อมูลครบ 100%:\nข้อมูลทุกเรคคอร์ดถูกจัดเก็บเรียบร้อย เตรียมพร้อมสำหรับกะการทำงานถัดไปครับ'
      }
    ]
  },
  {
    id: 'pack-8',
    name: '8. ทีมเวิร์ค & กำลังใจ',
    icon: '🤝',
    theme: 'from-pink-500 to-rose-600',
    stickers: [
      {
        id: 's8-1',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'ทีมสามัคคี',
        caption: 'ทีมสโตร์สามัคคี พลังรวมใจ 🤝',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-purple-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'team_hug',
        propsEmoji: '🤝',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ทีมสโตร์สามัคคี พลังรวมใจ',
        defaultAiReply: '### 🤝 One Team One Goal!\nการทำงานร่วมกันเป็นทีมทำให้คลังสินค้า OGA แข็งแกร่งและทำงานได้อย่างมีประสิทธิภาพสูงสุดครับ!'
      },
      {
        id: 's8-2',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'สู้ๆ นะครับ',
        caption: 'สู้ๆ ครับทุกคน ใกล้เสร็จแล้ว! 💪',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-rose-600 to-orange-500',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'fist_fighting',
        propsEmoji: '💪',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สู้ๆ ครับทุกคน ใกล้เสร็จแล้ว!',
        defaultAiReply: '### 💪 เป็นกำลังใจให้เต็มที่ครับ!\nอีกนิดเดียวก็จะเคลียร์ครบทุก Rack แล้ว สู้ไปด้วยกันครับ!'
      },
      {
        id: 's8-3',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'ขอบคุณทุกคน',
        caption: 'ขอบคุณทีมงานทุกคนมากๆ นะครับ 💖',
        themeColor: 'pink',
        bgGradient: 'from-rose-400 via-pink-500 to-purple-500',
        borderColor: 'border-rose-300',
        textColor: 'text-rose-950',
        badgeColor: 'bg-rose-100 text-rose-800',
        pose: 'thank_you_heart',
        propsEmoji: '💖',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ขอบคุณทีมงานทุกคนมากๆ นะครับ',
        defaultAiReply: '### 💖 ขอบคุณทุกความทุ่มเทครับ!\nผลงานสต็อกที่ถูกต้องแม่นยำเกิดขึ้นได้เพราะความใส่ใจของทุกคนในทีมครับ'
      },
      {
        id: 's8-4',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'มอบดอกไม้',
        caption: 'ยอดเยี่ยมที่สุดเลยครับ 💐',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-fuchsia-500 to-pink-500',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'flowers_bouquet',
        propsEmoji: '💐',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยอดเยี่ยมที่สุดเลยครับ มอบดอกไม้',
        defaultAiReply: '### 💐 มอบดอกไม้เป็นกำลังใจ!\nผลงานยอดเยี่ยมและปฏิบัติตามมาตรฐานได้อย่างสมบูรณ์แบบครับ'
      },
      {
        id: 's8-5',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'นับไวมาก',
        caption: 'นับได้ไวและเป๊ะมาก 👍',
        themeColor: 'sky',
        bgGradient: 'from-sky-400 via-blue-500 to-indigo-600',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'thumbsup_friend',
        propsEmoji: '👍',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: นับได้ไวและเป๊ะมาก',
        defaultAiReply: '### 👍 ชื่นชมทักษะความชำนาญ!\nคล่องแคล่วและแม่นยำ ถือเป็นตัวอย่างที่ดีของเพื่อนร่วมงานครับ'
      },
      {
        id: 's8-6',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'ทำงานสุขใจ',
        caption: 'ทำงานด้วยความสุขนะครับ 😊',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-yellow-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'happy_smile',
        propsEmoji: '😊',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ทำงานด้วยความสุขนะครับ',
        defaultAiReply: '### 😊 Happy Workplace:\nบรรยากาศการทำงานที่ดีนำมาซึ่งความแม่นยำและประสิทธิภาพที่ยอดเยี่ยมครับ'
      },
      {
        id: 's8-7',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'High Five',
        caption: 'High Five! สำเร็จไปด้วยกัน ✋',
        themeColor: 'navy',
        bgGradient: 'from-blue-600 via-indigo-700 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'high_five',
        propsEmoji: '✋',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: High Five! สำเร็จไปด้วยกัน',
        defaultAiReply: '### ✋ แตะมือฉลองความสำเร็จ!\nเคลียร์งานได้ตรงตามเป้าหมายเวลาเป๊ะเลยครับ'
      },
      {
        id: 's8-8',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'ไว้ใจทีมเรา',
        caption: 'ไว้ใจทีมเราได้เลย 😎',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-violet-600 to-indigo-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'cool_sunglasses',
        propsEmoji: '😎',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ไว้ใจทีมเราได้เลย',
        defaultAiReply: '### 😎 มือโปรตัวจริง!\nทีมงานคุณภาพพร้อมระบบ Mobile PDA ที่ทันสมัย มั่นใจได้ทุกการตรวจนับครับ'
      },
      {
        id: 's8-9',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'สู้ไม่ถอย',
        caption: 'ทีมคลังสินค้าสู้ไม่ถอย! 📣',
        themeColor: 'red',
        bgGradient: 'from-red-600 via-rose-600 to-orange-500',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'cheering_horn',
        propsEmoji: '📣',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ทีมคลังสินค้าสู้ไม่ถอย!',
        defaultAiReply: '### 📣 เสียงเชียร์ดังกึกก้อง!\nพลังทีมงานสุดยอดมากครับ งานยากแค่ไหนก็ผ่านฉลุยแน่นอน'
      },
      {
        id: 's8-10',
        packId: 'pack-8',
        packName: 'ทีมเวิร์ค & กำลังใจ',
        title: 'Super Store',
        caption: 'คุณคือ Super Storekeeper! ⭐',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-yellow-500 to-orange-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'super_star',
        propsEmoji: '⭐',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: คุณคือ Super Storekeeper!',
        defaultAiReply: '### ⭐ พนักงานดีเด่นประจำกะ!\nรักษามาตรฐานคุณภาพระดับนี้ไว้นะครับ เป็นแบบอย่างที่ดีมากๆ เลยครับ'
      }
    ]
  },
  {
    id: 'pack-9',
    name: '9. พักผ่อน & เติมพลัง',
    icon: '🧋',
    theme: 'from-amber-500 to-orange-500',
    stickers: [
      {
        id: 's9-1',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'ชานมไข่มุก',
        caption: 'พักเบรกกินชานมก่อนครับ 🧋',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-yellow-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'boba_tea',
        propsEmoji: '🧋',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พักเบรกกินชานมก่อนครับ',
        defaultAiReply: '### 🧋 ชานมไข่มุกหวานชื่นใจ!\nพักเบรกเติมน้ำตาลสักนิด ระบบ OGA จะพักหน้าจอและเซฟ Location ไว้ให้อัตโนมัติ ทานให้อร่อยครับ!'
      },
      {
        id: 's9-2',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'พักสายตา',
        caption: 'พักสายตา 10 นาที 😴',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-indigo-600 to-blue-700',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'sleeping',
        propsEmoji: '😴',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พักสายตา 10 นาที',
        defaultAiReply: '### 😴 พักผ่อนสายตาจากการมองหน้าจอ:\nการพักสายตาช่วยลดความล้าและเพิ่มสมาธิในการตรวจนับกะต่อไปได้ดีเยี่ยมครับ'
      },
      {
        id: 's9-3',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'แตงโมสดชื่น',
        caption: 'เติมความสดชื่นก่อนลุยต่อ 🍉',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-rose-600 to-emerald-500',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'watermelon',
        propsEmoji: '🍉',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: แตงโมสดชื่น เติมความสดชื่น',
        defaultAiReply: '### 🍉 สดชื่นคลายร้อน!\nเติมความสดชื่นในห้องพักพนักงานแล้วค่อยออกไปลุยต่อครับ'
      },
      {
        id: 's9-4',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'ดื่มน้ำเยอะๆ',
        caption: 'อย่าลืมดื่มน้ำเยอะๆ นะครับ 💧',
        themeColor: 'sky',
        bgGradient: 'from-cyan-400 via-sky-500 to-blue-600',
        borderColor: 'border-cyan-300',
        textColor: 'text-cyan-950',
        badgeColor: 'bg-cyan-100 text-cyan-800',
        pose: 'water_bottle',
        propsEmoji: '💧',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: อย่าลืมดื่มน้ำเยอะๆ นะครับ',
        defaultAiReply: '### 💧 ดื่มน้ำให้เพียงพอ:\nการทำงานในคลังสินค้าต้องเดินเยอะ อย่าลืมจิบน้ำสม่ำเสมอเพื่อรักษาสุขภาพนะครับ'
      },
      {
        id: 's9-5',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'พักเที่ยง',
        caption: 'ได้เวลาพักเที่ยงแล้ว! 🍛',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-amber-500',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'lunch_meal',
        propsEmoji: '🍛',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ได้เวลาพักเที่ยงแล้ว!',
        defaultAiReply: '### 🍛 พักรับประทานอาหารกลางวัน:\nทานอาหารให้อิ่มอร่อย เติมพลังให้เต็มที่แล้วช่วงบ่ายมาลุยกันต่อครับ!'
      },
      {
        id: 's9-6',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'ยืดเส้นยืดสาย',
        caption: 'บิดขี้เกียจ คลายเมื่อยสักนิด 🧘',
        themeColor: 'orange',
        bgGradient: 'from-amber-400 via-orange-500 to-teal-500',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'stretching',
        propsEmoji: '🧘',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ยืดเส้นยืดสาย คลายเมื่อย',
        defaultAiReply: '### 🧘 Ergonomics in Warehouse:\nยืดกล้ามเนื้อแขนและหลังตามหลักการยศาสตร์ ป้องกันอาการปวดเมื่อยจากการยกของครับ'
      },
      {
        id: 's9-7',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'ชาร์จแบต',
        caption: 'ชาร์จแบตพร้อมลุยต่อ 🔋',
        themeColor: 'sky',
        bgGradient: 'from-emerald-400 via-teal-500 to-sky-600',
        borderColor: 'border-emerald-300',
        textColor: 'text-emerald-950',
        badgeColor: 'bg-emerald-100 text-emerald-800',
        pose: 'battery_recharge',
        propsEmoji: '🔋',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ชาร์จแบตพร้อมลุยต่อ',
        defaultAiReply: '### 🔋 Battery 100% Recharged:\nทั้งคนและเครื่อง PDA พร้อมลุยตรวจนับต่อได้ยาวๆ ถึงสิ้นสุดกะเลยครับ'
      },
      {
        id: 's9-8',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'ฟังเพลงชิล',
        caption: 'ฟังเพลงสบายๆ ผ่อนคลาย 🎧',
        themeColor: 'purple',
        bgGradient: 'from-purple-500 via-indigo-600 to-pink-500',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'headphones',
        propsEmoji: '🎧',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ฟังเพลงสบายๆ ผ่อนคลาย',
        defaultAiReply: '### 🎧 ผ่อนคลายอารมณ์:\nฟังเพลงโปรดช่วงพักเบรกเพื่อเพิ่มพลังบวกในการทำงานครับ'
      },
      {
        id: 's9-9',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'พักผ่อนสุขใจ',
        caption: 'พักผ่อนอย่างมีความสุข 🏖️',
        themeColor: 'navy',
        bgGradient: 'from-blue-600 via-sky-600 to-indigo-800',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'beach_relax',
        propsEmoji: '🏖️',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พักผ่อนอย่างมีความสุข',
        defaultAiReply: '### 🏖️ เติมความสุขให้หัวใจ:\nพักผ่อนให้เต็มที่เพื่อเตรียมพร้อมรับมือกับทุกความท้าทายครับ'
      },
      {
        id: 's9-10',
        packId: 'pack-9',
        packName: 'พักผ่อน & เติมพลัง',
        title: 'หมดเวลาพัก',
        caption: 'หมดเวลาพัก ลุยงานต่อ! ⏰',
        themeColor: 'red',
        bgGradient: 'from-red-500 via-rose-600 to-orange-500',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'alarm_clock',
        propsEmoji: '⏰',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: หมดเวลาพัก ลุยงานต่อ!',
        defaultAiReply: '### ⏰ เสียงกระดิ่งเข้ากะทำงานดังขึ้นแล้ว:\nหยิบเครื่อง PDA แล้วมุ่งหน้าสู่โซนตรวจนับถัดไปได้เลยครับ!'
      }
    ]
  },
  {
    id: 'pack-10',
    name: '10. เลิกงาน & ส่งเวร',
    icon: '👋',
    theme: 'from-indigo-700 to-slate-900',
    stickers: [
      {
        id: 's10-1',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'เลิกงานแล้ว',
        caption: 'เลิกงานแล้วครับ บ๊ายบาย 👋',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'bye_wave',
        propsEmoji: '👋',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: เลิกงานแล้วครับ บ๊ายบาย',
        defaultAiReply: '### 👋 ขอบคุณสำหรับการทำงานหนักวันนี้!\nเลิกงานตรงเวลา สต็อกครบถ้วนสมบูรณ์ พักผ่อนให้สบายนะครับ บ๊ายบายครับ!'
      },
      {
        id: 's10-2',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'เสียบชาร์จ PDA',
        caption: 'ชาร์จแบตเครื่อง PDA พร้อมกะต่อไป 🔌',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-indigo-700 to-slate-800',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'dock_charger',
        propsEmoji: '🔌',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ชาร์จแบตเครื่อง PDA เข้าแท่นชาร์จ',
        defaultAiReply: '### 🔌 PDA Charging Cradle Routine:\nเสียบเครื่อง PDA เข้าแท่นชาร์จเรียบร้อย เพื่อให้พร้อมใช้งาน 100% สำหรับกะถัดไปตามระเบียบคลังครับ'
      },
      {
        id: 's10-3',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'ส่งมอบเวร',
        caption: 'ส่งมอบเวรตรวจนับเรียบร้อย 📋',
        themeColor: 'sky',
        bgGradient: 'from-sky-500 via-blue-600 to-indigo-700',
        borderColor: 'border-sky-300',
        textColor: 'text-sky-950',
        badgeColor: 'bg-sky-100 text-sky-800',
        pose: 'handover_report',
        propsEmoji: '📋',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ส่งมอบเวรตรวจนับเรียบร้อย',
        defaultAiReply: '### 📋 Shift Handover Complete:\nบันทึกรายการที่นับเสร็จและรายการที่ต้องนับต่อส่งมอบให้หัวหน้ากะต่อไปเรียบร้อยครับ'
      },
      {
        id: 's10-4',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'ล็อกคลังปลอดภัย',
        caption: 'ตรวจเช็คความปลอดภัย ล็อกคลัง 🔐',
        themeColor: 'red',
        bgGradient: 'from-red-600 via-rose-700 to-slate-900',
        borderColor: 'border-red-300',
        textColor: 'text-red-950',
        badgeColor: 'bg-red-100 text-red-800',
        pose: 'warehouse_lock',
        propsEmoji: '🔐',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ตรวจเช็คความปลอดภัย ล็อกคลัง',
        defaultAiReply: '### 🔐 Warehouse Security Check:\nปิดสวิตช์ไฟ, ตรวจสอบประตูทางเข้า-ออก และล็อกประตูคลังสินค้าตามข้อกำหนด ISO 27001 ครับ'
      },
      {
        id: 's10-5',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'ถอดหมวกพัก',
        caption: 'เหนื่อยมาทั้งวัน พักผ่อนได้! 🌙',
        themeColor: 'orange',
        bgGradient: 'from-amber-500 via-orange-600 to-purple-800',
        borderColor: 'border-amber-300',
        textColor: 'text-amber-950',
        badgeColor: 'bg-amber-100 text-amber-800',
        pose: 'remove_helmet',
        propsEmoji: '🌙',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: เหนื่อยมาทั้งวัน ถอดหมวกพักผ่อน',
        defaultAiReply: '### 🌙 Good Job Today!\nทำงานสำเร็จลุล่วงด้วยดี ถอดหมวกเซฟตี้แล้วไปพักผ่อนได้เลยครับ'
      },
      {
        id: 's10-6',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'กลับบ้านปลอดภัย',
        caption: 'เดินทางกลับบ้านปลอดภัยนะครับ 🚗',
        themeColor: 'pink',
        bgGradient: 'from-pink-400 via-rose-500 to-indigo-600',
        borderColor: 'border-pink-300',
        textColor: 'text-pink-950',
        badgeColor: 'bg-pink-100 text-pink-800',
        pose: 'driving_home',
        propsEmoji: '🚗',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: เดินทางกลับบ้านปลอดภัยนะครับ',
        defaultAiReply: '### 🚗 Safe Trip Home:\nขับขี่ปลอดภัย ถึงบ้านโดยสวัสดิภาพนะครับ'
      },
      {
        id: 's10-7',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'ส่งรายงานบอส',
        caption: 'สรุปยอดส่งผู้บริหารเรียบร้อย 💻',
        themeColor: 'navy',
        bgGradient: 'from-blue-700 via-indigo-800 to-slate-900',
        borderColor: 'border-blue-300',
        textColor: 'text-blue-950',
        badgeColor: 'bg-blue-100 text-blue-900',
        pose: 'boss_report',
        propsEmoji: '💻',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: สรุปยอดส่งผู้บริหารเรียบร้อย',
        defaultAiReply: '### 💻 Executive Summary Ready:\nรายงานสรุปสต็อกคงคลังและผลต่างส่งถึงอีเมลฝ่ายบริหารเรียบร้อยครับ'
      },
      {
        id: 's10-8',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'งานลุล่วง',
        caption: 'วันนี้ทำงานสำเร็จลุล่วง 🌟',
        themeColor: 'purple',
        bgGradient: 'from-purple-600 via-indigo-700 to-amber-500',
        borderColor: 'border-purple-300',
        textColor: 'text-purple-950',
        badgeColor: 'bg-purple-100 text-purple-800',
        pose: 'sparkle_night',
        propsEmoji: '🌟',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: วันนี้ทำงานสำเร็จลุล่วง',
        defaultAiReply: '### 🌟 Success & Mission Accomplished!\nภารกิจตรวจนับสต็อกวันนี้สำเร็จลุล่วง 100% สมบูรณ์แบบครับ'
      },
      {
        id: 's10-9',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'ไหว้งามๆ',
        caption: 'ขอบคุณสำหรับการทำงานหนักวันนี้ 🙏',
        themeColor: 'sky',
        bgGradient: 'from-cyan-400 via-sky-500 to-blue-700',
        borderColor: 'border-cyan-300',
        textColor: 'text-cyan-950',
        badgeColor: 'bg-cyan-100 text-cyan-800',
        pose: 'namaste_bow',
        propsEmoji: '🙏',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: ไหว้งามๆ ขอบคุณสำหรับการทำงานหนักวันนี้',
        defaultAiReply: '### 🙏 ขอขอบพระคุณเป็นอย่างยิ่งครับ!\nทีม AI OGA พร้อมให้บริการเสมอ แล้วพบกันใหม่ในวันพรุ่งนี้นะครับ'
      },
      {
        id: 's10-10',
        packId: 'pack-10',
        packName: 'เลิกงาน & ส่งเวร',
        title: 'กู๊ดไนท์',
        caption: 'พบกันใหม่กะพรุ่งนี้ครับ Good Night 🌜',
        themeColor: 'navy',
        bgGradient: 'from-indigo-800 via-slate-900 to-black',
        borderColor: 'border-indigo-400',
        textColor: 'text-indigo-950',
        badgeColor: 'bg-indigo-100 text-indigo-900',
        pose: 'good_night',
        propsEmoji: '🌜',
        aiPrompt: 'ผู้ใช้ส่งสติ๊กเกอร์น้องช้าง OGA: พบกันใหม่กะพรุ่งนี้ครับ Good Night',
        defaultAiReply: '### 🌜 ราตรีสวัสดิ์ครับ!\nหลับฝันดี พักผ่อนให้เต็มอิ่ม แล้วพบกันใหม่ในกะการทำงานวันพรุ่งนี้นะครับ Good Night! 🌟'
      }
    ]
  }
];
